name: Build and Release

on:
  push:
    tags:
      - 'v*'  # v1.0.0 のようなタグでトリガーされます

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # 必要に応じて変更

      - name: Restore dependencies
        run: dotnet restore LostWorldTracker.sln

      - name: Build project
        run: dotnet publish LostWorldTracker/LostWorldTracker.csproj -c Release -r win-x64 -p:PublishSingleFile=true --output out

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          files: out/LostWorldTracker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
