name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 例: v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/LostWorldTracker.sln

      - name: Publish application
        run: |
          dotnet publish src/LostWorldTracker/LostWorldTracker.csproj -c Release -o out
          Copy-Item -Path 'docs\*' -Destination 'out' -Recurse -Force

      - name: ZIP outputs
        run: Compress-Archive -Path out\* -DestinationPath LostWorldTracker.zip

      - name: Release ZIP
        uses: softprops/action-gh-release@v2
        with:
          files: LostWorldTracker.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
